### ISSUE TITLE
registration.php not setup in autoload files directive

### ISSUE THREAD

**Issue by ClaudiuCreanga** [magento/marketplace-tools#6]
I am trying to submit an extension to the marketplace and I get this error:
registration.php not setup in autoload files directive.

When I run your test in console I get:

"registration.php" not found in 'files' field of the 'autoload' directive
 "magento2-stockists-extension-master/etc/module.xml" is missing.

My composer.json:
```
"autoload": {
    "files": [ "src/registration.php" ],
    "psr-4": {
      "vendor\\name\\": "src/"
    }
  }
```
file structure:
```
-composer.json
-src
 | -etc/
 | -registration.php
```

The extension installs itself fine. Why doesn't the test look into src folder? How can I submit my extension?

Thanks!

**Comment by ClaudiuCreanga** [comment]
I just removed my custom structure and inserted everything into the main folder.
I just wonder why this must be the case. It basically means that there is one more step from updating the module on github / packagist and submit an updated version to the marketplace.

**Comment by i-daszkowski** [comment]
Currently, this structure is not supported by the Component Manager. Since the Marketplace supports installation via the Component Manager, we are unable to accept packages of this structure.
